'use client';

import { useState } from 'react';
import { Activity, ArrowDown, ArrowUp, CirclePlay, Pause, Plus, Save, ShieldCheck, Trash2, Workflow as WorkflowIcon } from 'lucide-react';
import type { StudioWorkflow } from '@/lib/tools/automation-studio/service';

type CatalogItem = { type: string; name: string; description: string; risk: string };
type DraftStep = { name: string; action_type: string; action_config: Record<string, unknown>; retry_limit: number; continue_on_error: boolean };
const emptyStep = (type = 'core.set_value'): DraftStep => ({ name: 'New step', action_type: type, action_config: type === 'core.set_value' ? { key: 'result', value: 'ready' } : {}, retry_limit: 1, continue_on_error: false });

export default function AutomationBuilder({ databaseReady, workflows, catalog }: { databaseReady: boolean; workflows: StudioWorkflow[]; catalog: CatalogItem[] }) {
  const [editingId, setEditingId] = useState<string | null>(null);
  const [name, setName] = useState('My automation');
  const [description, setDescription] = useState('');
  const [triggerType, setTriggerType] = useState('manual');
  const [intervalMinutes, setIntervalMinutes] = useState(60);
  const [dailyTime, setDailyTime] = useState('09:00');
  const [dailyLimit, setDailyLimit] = useState(24);
  const [steps, setSteps] = useState<DraftStep[]>([emptyStep()]);
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);

  function edit(workflow: StudioWorkflow) {
    setEditingId(workflow.id); setName(workflow.name); setDescription(workflow.description); setTriggerType(workflow.trigger_type); setDailyLimit(workflow.daily_run_limit);
    setIntervalMinutes(Number(workflow.trigger_config.interval_minutes || 60)); setDailyTime(String(workflow.trigger_config.time_utc || '09:00'));
    setSteps((workflow.automation_steps || []).map((step) => ({ name: step.name, action_type: step.action_type, action_config: step.action_config || {}, retry_limit: step.retry_limit, continue_on_error: step.continue_on_error })));
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
  function updateStep(index: number, patch: Partial<DraftStep>) { setSteps((current) => current.map((step, i) => i === index ? { ...step, ...patch } : step)); }
  function move(index: number, delta: number) { setSteps((current) => { const next = [...current]; const target = index + delta; if (target < 0 || target >= next.length) return current; [next[index], next[target]] = [next[target], next[index]]; return next; }); }
  function actionConfig(index: number, step: DraftStep) {
    if (step.action_type === 'core.set_value') return <div className="grid gap-2 sm:grid-cols-2"><MiniInput label="Context key" value={String(step.action_config.key || '')} onChange={(value) => updateStep(index, { action_config: { ...step.action_config, key: value } })} /><MiniInput label="Value" value={String(step.action_config.value ?? '')} onChange={(value) => updateStep(index, { action_config: { ...step.action_config, value } })} /></div>;
    if (step.action_type === 'core.condition') return <div className="grid gap-2 sm:grid-cols-3"><MiniInput label="Context field" value={String(step.action_config.field || '')} onChange={(value) => updateStep(index, { action_config: { ...step.action_config, field: value } })} /><label className="space-y-1"><span className="text-[10px] text-slate-500">Operator</span><select value={String(step.action_config.operator || 'exists')} onChange={(event) => updateStep(index, { action_config: { ...step.action_config, operator: event.target.value } })} className="w-full rounded-lg border border-white/10 bg-[#090b11] px-2 py-2 text-xs"><option value="exists">Exists</option><option value="equals">Equals</option><option value="not_equals">Not equals</option></select></label><MiniInput label="Compare value" value={String(step.action_config.value ?? '')} onChange={(value) => updateStep(index, { action_config: { ...step.action_config, value } })} /></div>;
    if (step.action_type === 'core.public_webhook') return <MiniInput label="Public HTTPS webhook URL" value={String(step.action_config.url || '')} onChange={(value) => updateStep(index, { action_config: { url: value } })} />;
    return <p className="text-xs text-slate-600">This guarded action uses the selected AurionStack module’s existing campaign, consent, limits, and suppression settings.</p>;
  }
  async function save() {
    setBusy(true); setMessage('');
    const trigger_config = triggerType === 'interval' ? { interval_minutes: intervalMinutes } : triggerType === 'daily' ? { time_utc: dailyTime } : {};
    const response = await fetch('/api/tools/automation-studio/workflows', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: editingId, name, description, trigger_type: triggerType, trigger_config, daily_run_limit: dailyLimit, steps }) });
    const result = await response.json(); setBusy(false); setMessage(response.ok ? 'Saved as draft. Reloading…' : result.error || 'Save failed.'); if (response.ok) window.location.reload();
  }
  async function action(workflow: StudioWorkflow, actionName: 'activate' | 'pause' | 'run') {
    let confirmation: string | undefined;
    const risks = (workflow.automation_steps || []).map((step) => catalog.find((item) => item.type === step.action_type)?.risk);
    if (actionName === 'activate') { const required = risks.includes('outreach') ? 'ACTIVATE OUTREACH AUTOMATION' : 'ACTIVATE AUTOMATION'; confirmation = window.prompt(`Type ${required}`) || undefined; if (!confirmation) return; }
    if (actionName === 'run' && risks.some((risk) => risk && risk !== 'safe')) { const required = risks.includes('outreach') ? 'RUN OUTREACH AUTOMATION' : 'RUN AUTOMATION'; confirmation = window.prompt(`Type ${required}`) || undefined; if (!confirmation) return; }
    setBusy(true); const response = await fetch('/api/tools/automation-studio/workflows', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: workflow.id, action: actionName, confirmation }) }); const result = await response.json(); setBusy(false); setMessage(response.ok ? `Workflow ${result.status}.` : result.error || 'Action failed.'); if (response.ok) window.location.reload();
  }

  return <div className="space-y-7">
    <section className="rounded-3xl border border-violet-300/10 bg-[linear-gradient(120deg,rgba(139,92,246,.14),rgba(17,20,28,.82)_52%,rgba(59,130,246,.08))] p-6 sm:p-8"><div className="inline-flex items-center gap-2 rounded-full border border-violet-300/15 bg-violet-300/[0.06] px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-violet-200"><WorkflowIcon className="size-3.5" /> No-code workflow engine</div><h1 className="mt-5 text-3xl font-semibold tracking-[-0.03em] text-white sm:text-4xl">Build the automation your operation needs.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">Compose schedules, conditions, transforms, public webhooks, and guarded AurionStack actions. Drafts are inert; every run is tenant-scoped and fully logged.</p></section>
    {!databaseReady && <div className="rounded-2xl border border-amber-300/15 bg-amber-300/[0.05] px-5 py-4 text-sm text-amber-200">Apply migration 013 before creating workflows.</div>}
    <section className="rounded-2xl border border-white/[0.07] bg-[#10131a] p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-white">{editingId ? 'Edit workflow' : 'New workflow'}</h2><p className="mt-1 text-xs text-slate-500">Saving always returns the workflow to draft.</p></div><ShieldCheck className="size-5 text-violet-300" /></div>
      <div className="mt-5 grid gap-4 sm:grid-cols-2"><MiniInput label="Workflow name" value={name} onChange={setName} /><MiniInput label="Description" value={description} onChange={setDescription} /><label className="space-y-2"><span className="text-xs text-slate-400">Trigger</span><select value={triggerType} onChange={(event) => setTriggerType(event.target.value)} className="w-full rounded-xl border border-white/10 bg-[#080a10] px-3 py-2.5 text-sm"><option value="manual">Manual</option><option value="interval">Every N minutes</option><option value="daily">Daily at UTC time</option></select></label>{triggerType === 'interval' ? <MiniInput label="Interval minutes (minimum 5)" type="number" value={String(intervalMinutes)} onChange={(value) => setIntervalMinutes(Number(value))} /> : triggerType === 'daily' ? <MiniInput label="Daily UTC time" type="time" value={dailyTime} onChange={setDailyTime} /> : <div />}<MiniInput label="Maximum runs per UTC day" type="number" value={String(dailyLimit)} onChange={(value) => setDailyLimit(Number(value))} /></div>
      <div className="mt-6 space-y-3">{steps.map((step, index) => <div key={index} className="rounded-xl border border-white/[0.07] bg-[#090b11] p-4"><div className="flex flex-wrap items-center gap-2"><span className="grid size-7 place-items-center rounded-lg bg-violet-400/10 text-xs font-semibold text-violet-300">{index + 1}</span><input value={step.name} onChange={(event) => updateStep(index, { name: event.target.value })} className="min-w-36 flex-1 bg-transparent text-sm font-medium text-white outline-none" /><select value={step.action_type} onChange={(event) => { const type = event.target.value; updateStep(index, { action_type: type, action_config: emptyStep(type).action_config }); }} className="rounded-lg border border-white/10 bg-[#10131a] px-2 py-2 text-xs">{catalog.map((item) => <option key={item.type} value={item.type}>{item.name} · {item.risk}</option>)}</select><button onClick={() => move(index, -1)} aria-label="Move up"><ArrowUp className="size-4 text-slate-500" /></button><button onClick={() => move(index, 1)} aria-label="Move down"><ArrowDown className="size-4 text-slate-500" /></button><button onClick={() => setSteps((current) => current.filter((_, i) => i !== index))} aria-label="Remove"><Trash2 className="size-4 text-rose-400" /></button></div><div className="mt-3">{actionConfig(index, step)}</div><label className="mt-3 flex items-center gap-2 text-xs text-slate-500"><input type="checkbox" checked={step.continue_on_error} onChange={(event) => updateStep(index, { continue_on_error: event.target.checked })} /> Continue if this step fails</label></div>)}</div>
      <div className="mt-4 flex flex-wrap gap-3"><button onClick={() => setSteps((current) => [...current, emptyStep()])} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm text-slate-300"><Plus className="size-4" /> Add step</button><button disabled={busy || !databaseReady} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-violet-500 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Save className="size-4" /> Save draft</button><span className="self-center text-xs text-slate-500">{message}</span></div>
    </section>
    <section><h2 className="mb-4 text-sm font-semibold text-white">Your workflows</h2><div className="grid gap-4 lg:grid-cols-2">{workflows.map((workflow) => <div key={workflow.id} className="rounded-2xl border border-white/[0.07] bg-[#10131a] p-5"><div className="flex items-start justify-between"><div><h3 className="font-semibold text-white">{workflow.name}</h3><p className="mt-1 text-xs text-slate-500">{workflow.trigger_type} · {(workflow.automation_steps || []).length} steps</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase ${workflow.status === 'active' ? 'bg-emerald-400/10 text-emerald-300' : 'bg-amber-300/10 text-amber-300'}`}>{workflow.status}</span></div><p className="mt-4 text-sm text-slate-500">{workflow.description || 'No description'}</p><div className="mt-5 flex flex-wrap gap-2"><button onClick={() => edit(workflow)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-300">Edit</button><button disabled={busy} onClick={() => action(workflow, 'run')} className="inline-flex items-center gap-1.5 rounded-lg border border-violet-300/15 px-3 py-2 text-xs text-violet-200"><CirclePlay className="size-3.5" /> Run</button>{workflow.status === 'active' ? <button onClick={() => action(workflow, 'pause')} className="inline-flex items-center gap-1.5 rounded-lg border border-amber-300/15 px-3 py-2 text-xs text-amber-200"><Pause className="size-3.5" /> Pause</button> : <button onClick={() => action(workflow, 'activate')} className="inline-flex items-center gap-1.5 rounded-lg border border-emerald-300/15 px-3 py-2 text-xs text-emerald-200"><Activity className="size-3.5" /> Activate</button>}</div><div className="mt-4 border-t border-white/[0.06] pt-3 text-xs text-slate-600">Last run: {workflow.last_run_at ? new Date(workflow.last_run_at).toLocaleString() : 'Never'} · Next: {workflow.next_run_at ? new Date(workflow.next_run_at).toLocaleString() : 'Not scheduled'}</div></div>)}{!workflows.length && <p className="text-sm text-slate-600">No workflows yet.</p>}</div></section>
  </div>;
}

function MiniInput({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="space-y-1"><span className="text-[10px] text-slate-500">{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-lg border border-white/10 bg-[#090b11] px-3 py-2 text-sm text-white outline-none focus:border-violet-400/40" /></label>; }
